import { createServerClient } from '@supabase/ssr'
import { cookies } from 'next/headers'
import { NextResponse } from 'next/server'

const ADMIN_EMAIL = 'marcelomord@gmail.com'

const SEED_BANNERS = [
  { partner_name: 'Amazon Baby', image_url: 'https://picsum.photos/seed/amazon-baby-banner/800/280', link_url: 'https://www.amazon.com.br/s?k=produtos+para+bebe&tag=memorabebe-20', is_active: true, sort_order: 0 },
  { partner_name: 'Amazon Roupinhas', image_url: 'https://picsum.photos/seed/roupinhas-banner/800/280', link_url: 'https://www.amazon.com.br/s?k=roupinhas+bebe&tag=memorabebe-20', is_active: true, sort_order: 1 },
  { partner_name: 'Amazon Brinquedos', image_url: 'https://picsum.photos/seed/brinquedos-banner/800/280', link_url: 'https://www.amazon.com.br/s?k=brinquedos+educativos+bebe&tag=memorabebe-20', is_active: true, sort_order: 2 },
  { partner_name: 'Amazon Higiene Baby', image_url: 'https://picsum.photos/seed/higiene-banner/800/280', link_url: 'https://www.amazon.com.br/s?k=higiene+bebe+kit&tag=memorabebe-20', is_active: true, sort_order: 3 },
  { partner_name: 'Amazon Quarto Bebê', image_url: 'https://picsum.photos/seed/quarto-bebe-banner/800/280', link_url: 'https://www.amazon.com.br/s?k=quarto+bebe+decoracao&tag=memorabebe-20', is_active: true, sort_order: 4 },
]

const SEED_PRODUCTS = [
  // ── Roupinhas ─────────────────────────────────────────────────────────────
  { partner_name: 'Amazon', title: 'Body Manga Longa Branco — Pack 5 un.', description: 'Algodão macio 100%, ideal para o frio. Fechamento por press.', price: 79.90, original_price: 99.90, image_url: 'https://picsum.photos/seed/body-branco-ml/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=body+manga+longa+bebe+branco&tag=memorabebe-20', category: 'Roupinhas', is_active: true, is_featured: true, sort_order: 0 },
  { partner_name: 'Amazon', title: 'Macacão Plush Listrado 0–3 meses', description: 'Quentinho, macio e com fechamento por zíper para trocas fáceis.', price: 59.90, original_price: null, image_url: 'https://picsum.photos/seed/macacao-listrado/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=macacao+plush+bebe&tag=memorabebe-20', category: 'Roupinhas', is_active: true, is_featured: false, sort_order: 1 },
  { partner_name: 'Amazon', title: 'Set Bodies Coloridos — 7 Peças Algodão', description: 'Kit com 7 bodies coloridos em algodão premium, tamanhos RN a 9M.', price: 89.90, original_price: 119.90, image_url: 'https://picsum.photos/seed/bodies-coloridos/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=kit+body+bebe+colorido&tag=memorabebe-20', category: 'Roupinhas', is_active: true, is_featured: true, sort_order: 2 },
  { partner_name: 'Amazon', title: 'Pijama Quentinho com Pé Antiderrapante', description: 'Perfeito para noites frias, solinha antiderrapante e zíper duplo.', price: 69.90, original_price: null, image_url: 'https://picsum.photos/seed/pijama-pe/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=pijama+bebe+pe+antiderrapante&tag=memorabebe-20', category: 'Roupinhas', is_active: true, is_featured: false, sort_order: 3 },
  { partner_name: 'Amazon', title: 'Kit Enxoval Completo — 14 Peças', description: 'Tudo que o bebê precisa: bodies, macacões, meias e touca.', price: 149.90, original_price: 189.90, image_url: 'https://picsum.photos/seed/enxoval-kit/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=kit+enxoval+bebe+completo&tag=memorabebe-20', category: 'Roupinhas', is_active: true, is_featured: false, sort_order: 4 },
  // ── Brinquedos ────────────────────────────────────────────────────────────
  { partner_name: 'Amazon', title: 'Mordedor de Silicone BPA Free — 6 Formas', description: 'Seguro, livre de BPA. Ajuda no alívio da dentição.', price: 39.90, original_price: 49.90, image_url: 'https://picsum.photos/seed/mordedor-silicone/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=mordedor+silicone+bpa+free+bebe&tag=memorabebe-20', category: 'Brinquedos', is_active: true, is_featured: true, sort_order: 5 },
  { partner_name: 'Amazon', title: 'Sophie la Girafe — Mordedor Clássico', description: 'O mordedor mais famoso do mundo, feito de borracha natural.', price: 129.90, original_price: 159.90, image_url: 'https://picsum.photos/seed/sophie-girafe/300/300', affiliate_url: 'https://www.amazon.com.br/dp/B00IWN6JYE?tag=memorabebe-20', category: 'Brinquedos', is_active: true, is_featured: true, sort_order: 6 },
  { partner_name: 'Amazon', title: 'Tapete de Atividades Musical com Arco', description: 'Estimula o desenvolvimento sensorial com sons, luzes e texturas.', price: 189.90, original_price: 249.90, image_url: 'https://picsum.photos/seed/tapete-atividades/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=tapete+atividades+musical+bebe&tag=memorabebe-20', category: 'Brinquedos', is_active: true, is_featured: false, sort_order: 7 },
  { partner_name: 'Amazon', title: 'Móbile de Berço Musical com Luz', description: 'Gira suavemente com música e projeta luzes de estrelas no teto.', price: 149.90, original_price: 199.90, image_url: 'https://picsum.photos/seed/mobile-berce/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=mobile+berco+musical+luz&tag=memorabebe-20', category: 'Brinquedos', is_active: true, is_featured: false, sort_order: 8 },
  { partner_name: 'Amazon', title: 'Set de Brinquedos para o Banho — 8 Peças', description: 'Animais coloridos que tornam o banho mais divertido e seguro.', price: 49.90, original_price: 69.90, image_url: 'https://picsum.photos/seed/brinquedo-banho/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=brinquedos+banho+bebe&tag=memorabebe-20', category: 'Brinquedos', is_active: true, is_featured: false, sort_order: 9 },
  // ── Higiene ───────────────────────────────────────────────────────────────
  { partner_name: 'Amazon', title: 'Bepantol Baby Pomada Preventiva 120g', description: 'Previne e trata assaduras com vitamina B5. Dermatologicamente testada.', price: 34.90, original_price: 45.90, image_url: 'https://picsum.photos/seed/bepantol-baby/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=bepantol+baby+pomada&tag=memorabebe-20', category: 'Higiene', is_active: true, is_featured: false, sort_order: 10 },
  { partner_name: 'Amazon', title: "Shampoo Johnson's Baby 400ml", description: 'Fórmula suave sem lágrimas, pH neutro. Dermatologicamente testado.', price: 19.90, original_price: null, image_url: 'https://picsum.photos/seed/shampoo-johnsons/300/300', affiliate_url: "https://www.amazon.com.br/s?k=shampoo+johnsons+baby&tag=memorabebe-20", category: 'Higiene', is_active: true, is_featured: false, sort_order: 11 },
  { partner_name: 'Amazon', title: 'Lenços Umedecidos Huggies — 6 Pacotes', description: 'Com extratos naturais, pH balanceado para a pele delicada do bebê.', price: 79.90, original_price: 99.90, image_url: 'https://picsum.photos/seed/lencos-huggies/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=lencos+umedecidos+huggies+bebe&tag=memorabebe-20', category: 'Higiene', is_active: true, is_featured: true, sort_order: 12 },
  { partner_name: 'Amazon', title: 'Creme Hidratante Mustela 300ml', description: 'Hidratação 24h para a pele sensível do bebê. Sem parabenos.', price: 89.90, original_price: 119.90, image_url: 'https://picsum.photos/seed/mustela-creme/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=mustela+hidratante+bebe&tag=memorabebe-20', category: 'Higiene', is_active: true, is_featured: false, sort_order: 13 },
  { partner_name: 'Amazon', title: 'Sabonete Líquido Dove Baby 400ml', description: 'Limpeza suave e hidratante, com ¼ de creme hidratante.', price: 22.90, original_price: null, image_url: 'https://picsum.photos/seed/dove-baby/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=sabonete+dove+baby&tag=memorabebe-20', category: 'Higiene', is_active: true, is_featured: false, sort_order: 14 },
  // ── Alimentação ───────────────────────────────────────────────────────────
  { partner_name: 'Amazon', title: 'Colheres de Silicone para Papinha — 4 un.', description: 'Ponta macia que protege as gengivas. BPA free, lavável na lava-louça.', price: 29.90, original_price: 39.90, image_url: 'https://picsum.photos/seed/colher-silicone/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=colher+silicone+papinha+bebe&tag=memorabebe-20', category: 'Alimentação', is_active: true, is_featured: false, sort_order: 15 },
  { partner_name: 'Amazon', title: 'Conjunto de Potes para Papinha — 8 un.', description: 'Herméticos, empilháveis e seguros para microondas e freezer.', price: 49.90, original_price: 69.90, image_url: 'https://picsum.photos/seed/potes-papinha/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=potes+papinha+bebe&tag=memorabebe-20', category: 'Alimentação', is_active: true, is_featured: false, sort_order: 16 },
  { partner_name: 'Amazon', title: 'Babador Impermeável com Bolso Silicone', description: 'Fácil de limpar, mangas longas e bolso grande para coletar restos.', price: 44.90, original_price: 59.90, image_url: 'https://picsum.photos/seed/babador-silicone/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=babador+impermeavel+silicone+bebe&tag=memorabebe-20', category: 'Alimentação', is_active: true, is_featured: true, sort_order: 17 },
  { partner_name: 'Amazon', title: "Mamadeira Dr. Brown's Natural 150ml", description: 'Sistema de ventilação interna reduz cólicas, gases e refluxo.', price: 69.90, original_price: 89.90, image_url: 'https://picsum.photos/seed/mamadeira-drbrowns/300/300', affiliate_url: "https://www.amazon.com.br/s?k=mamadeira+dr+browns&tag=memorabebe-20", category: 'Alimentação', is_active: true, is_featured: true, sort_order: 18 },
  { partner_name: 'Amazon', title: 'Copo de Transição 360° Antivazamento 300ml', description: 'Qualquer ponto do bico libera líquido. Ideal a partir de 6 meses.', price: 39.90, original_price: 54.90, image_url: 'https://picsum.photos/seed/copo-360/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=copo+transicao+360+bebe&tag=memorabebe-20', category: 'Alimentação', is_active: true, is_featured: false, sort_order: 19 },
  // ── Quarto ────────────────────────────────────────────────────────────────
  { partner_name: 'Amazon', title: 'Berço Portátil Desmontável com Colchonete', description: 'Leve, fácil de montar e levar em viagens. Cabe em qualquer quarto.', price: 399.90, original_price: 549.90, image_url: 'https://picsum.photos/seed/berco-portatil/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=berco+portatil+bebe+desmontavel&tag=memorabebe-20', category: 'Quarto', is_active: true, is_featured: true, sort_order: 20 },
  { partner_name: 'Amazon', title: 'Travesseiro Anti-Refluxo para Bebê', description: 'Inclinação de 15° reduz refluxo e cólicas. Capa lavável.', price: 99.90, original_price: 139.90, image_url: 'https://picsum.photos/seed/travesseiro-refluxo/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=travesseiro+anti+refluxo+bebe&tag=memorabebe-20', category: 'Quarto', is_active: true, is_featured: false, sort_order: 21 },
  { partner_name: 'Amazon', title: 'Projetor de Estrelas Musical Giratório', description: 'Projeta constelações no teto com música relaxante. Timer automático.', price: 149.90, original_price: 199.90, image_url: 'https://picsum.photos/seed/projetor-estrelas/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=projetor+estrelas+bebe+musical&tag=memorabebe-20', category: 'Quarto', is_active: true, is_featured: false, sort_order: 22 },
  { partner_name: 'Amazon', title: 'Jogo de Lençol para Berço — 3 Peças Percal', description: 'Algodão percal 180 fios, hipoalergênico, lavável a 60°C.', price: 89.90, original_price: 119.90, image_url: 'https://picsum.photos/seed/lencol-berco/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=jogo+lencol+berco+bebe&tag=memorabebe-20', category: 'Quarto', is_active: true, is_featured: false, sort_order: 23 },
  { partner_name: 'Amazon', title: 'Monitor Bebê Wi-Fi com Câmera HD', description: 'Visão noturna, transmissão ao vivo pelo celular, alerta de som.', price: 349.90, original_price: 499.90, image_url: 'https://picsum.photos/seed/monitor-wifi/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=monitor+bebe+wifi+camera+hd&tag=memorabebe-20', category: 'Quarto', is_active: true, is_featured: true, sort_order: 24 },
  // ── Passeio ───────────────────────────────────────────────────────────────
  { partner_name: 'Amazon', title: 'Carrinho de Bebê Leve 7kg Dobrável', description: 'Compacto, dobra com uma mão, cabe no porta-malas. Até 15kg.', price: 899.90, original_price: 1299.90, image_url: 'https://picsum.photos/seed/carrinho-leve/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=carrinho+bebe+leve+dobravel&tag=memorabebe-20', category: 'Passeio', is_active: true, is_featured: true, sort_order: 25 },
  { partner_name: 'Amazon', title: 'Mochila Maternidade 20L Impermeável', description: 'Organizada, impermeável, com porta USB e forro térmico para mamadeira.', price: 199.90, original_price: 279.90, image_url: 'https://picsum.photos/seed/mochila-maternidade/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=mochila+maternidade+impermeavel&tag=memorabebe-20', category: 'Passeio', is_active: true, is_featured: false, sort_order: 26 },
  { partner_name: 'Amazon', title: 'Cadeirinha Auto Bebê Conforto 0–13kg', description: 'Aprovada pelo INMETRO, instala em segundos com cinto de 3 pontos.', price: 499.90, original_price: 699.90, image_url: 'https://picsum.photos/seed/cadeirinha-auto/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=cadeirinha+auto+bebe+conforto&tag=memorabebe-20', category: 'Passeio', is_active: true, is_featured: true, sort_order: 27 },
  { partner_name: 'Amazon', title: 'Capa de Chuva Universal para Carrinho', description: 'Encaixa em qualquer carrinho, ventilação lateral, fácil de guardar.', price: 79.90, original_price: 99.90, image_url: 'https://picsum.photos/seed/capa-chuva-carrinho/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=capa+de+chuva+carrinho+bebe&tag=memorabebe-20', category: 'Passeio', is_active: true, is_featured: false, sort_order: 28 },
  { partner_name: 'Amazon', title: 'Bandeja Organizadora para Carrinho', description: 'Porta-copos, compartimentos e gancho para sacolas. Universal.', price: 59.90, original_price: 79.90, image_url: 'https://picsum.photos/seed/bandeja-carrinho/300/300', affiliate_url: 'https://www.amazon.com.br/s?k=bandeja+organizadora+carrinho+bebe&tag=memorabebe-20', category: 'Passeio', is_active: true, is_featured: false, sort_order: 29 },
]

export async function POST() {
  const cookieStore = await cookies()
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    { cookies: { getAll: () => cookieStore.getAll(), setAll: (c) => { try { c.forEach(({ name, value, options }) => cookieStore.set(name, value, options)) } catch {} } } }
  )

  const { data: { user } } = await supabase.auth.getUser()
  if (!user || user.email !== ADMIN_EMAIL) {
    return NextResponse.json({ error: 'Não autorizado' }, { status: 403 })
  }

  const { error: bErr } = await supabase.from('partner_banners').insert(SEED_BANNERS)
  const { error: pErr } = await supabase.from('partner_products').insert(SEED_PRODUCTS)

  if (bErr || pErr) {
    return NextResponse.json({ error: bErr?.message || pErr?.message }, { status: 500 })
  }

  return NextResponse.json({ ok: true, banners: SEED_BANNERS.length, products: SEED_PRODUCTS.length })
}
